[ERROR] 2019-10-30 12:46:11.724692: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6278>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.730605: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe66a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.955706: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.959139: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6d68>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.962542: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffc50>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.966527: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffe80>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.969493: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b66320>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:11.972170: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b66ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:14.194862: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:14.203921: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff358>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.209031: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff898>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.905934: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.909932: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6080>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.914006: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffcc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.982599: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b660f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:16.987260: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b662e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:17.216815: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff390>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:17.221478: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfff98>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:18.994246: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffc88>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.000207: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffda0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.005856: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6048>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.230762: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfd860>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.234814: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe67f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.237758: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b67710>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.240687: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b67eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.243153: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b726a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.246378: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe67f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.249140: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfd748>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.252064: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfff98>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.255048: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff278>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.257910: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b721d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.260969: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b72eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.263762: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b6f6a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:19.266977: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffe10>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:20.271051: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abffd30>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:22.267116: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:23.275718: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:23.279234: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:23.281769: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff278>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:25.287429: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b6a438>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:25.295107: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff278>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:25.298187: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.153343: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.161435: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfff60>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.304119: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe9630>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.310478: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6390>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.313359: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6470>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.316084: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /places/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b6ab00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:26.318820: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b742e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:27.165302: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff0b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:27.168309: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff438>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:27.171909: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff400>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:27.175059: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6898>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.325378: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6748>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.329000: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.332459: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfff98>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.335976: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfffd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.339275: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b74320>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.342172: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b74b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.344880: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b602e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.347636: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe9b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.350540: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abff4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:29.353219: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abfd860>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:31.182686: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:31.187361: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b69358>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:31.191734: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b69b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:31.195654: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b742e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:31.358474: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6390>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:36.368643: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:36.375402: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b60b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:36.378551: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a57b6e2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[ERROR] 2019-10-30 12:46:36.381430: HTTPSConnectionPool(host='10.100.4.187', port=8243): Max retries exceeded with url: /news/1/menu (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a5abe6e80>: Failed to establish a new connection: [Errno 111] Connection refused',))
[INFO] 2019-10-30 13:06:47.606906: process_7 stopped. Execution finished!
[INFO] 2019-10-30 13:07:55.065549: process_4 stopped. Execution finished!
[INFO] 2019-10-30 13:08:12.089548: process_19 stopped. Execution finished!
[INFO] 2019-10-30 13:09:11.452798: process_11 stopped. Execution finished!
[INFO] 2019-10-30 13:09:35.758347: process_9 stopped. Execution finished!
[INFO] 2019-10-30 13:10:19.861999: process_17 stopped. Execution finished!
[INFO] 2019-10-30 13:10:29.647290: process_5 stopped. Execution finished!
[INFO] 2019-10-30 13:10:31.699434: process_2 stopped. Execution finished!
[INFO] 2019-10-30 13:10:39.757678: process_0 stopped. Execution finished!
[INFO] 2019-10-30 13:10:40.551889: process_16 stopped. Execution finished!
[INFO] 2019-10-30 13:10:46.042023: process_8 stopped. Execution finished!
[INFO] 2019-10-30 13:10:54.737336: process_14 stopped. Execution finished!
[INFO] 2019-10-30 13:10:59.243683: process_10 stopped. Execution finished!
[INFO] 2019-10-30 13:10:59.997065: process_15 stopped. Execution finished!
[INFO] 2019-10-30 13:11:04.398739: process_3 stopped. Execution finished!
[INFO] 2019-10-30 13:12:44.026244: process_13 stopped. Execution finished!
[INFO] 2019-10-30 13:14:16.678533: process_18 stopped. Execution finished!
[INFO] 2019-10-30 13:19:30.757198: process_6 stopped. Execution finished!
[INFO] 2019-10-30 13:25:16.018356: process_12 stopped. Execution finished!
[INFO] 2019-10-30 13:27:29.835288: process_1 stopped. Execution finished!
[INFO] 2019-10-30 14:17:31.352998: Scenario process process_0 started!
[INFO] 2019-10-30 14:17:31.354567: Scenario process process_1 started!
[INFO] 2019-10-30 14:17:31.355784: Scenario process process_2 started!
[INFO] 2019-10-30 14:17:31.357061: Scenario process process_3 started!
[INFO] 2019-10-30 14:17:31.359064: Scenario process process_4 started!
[INFO] 2019-10-30 14:17:31.363059: Scenario process process_6 started!
[INFO] 2019-10-30 14:17:31.366460: Scenario process process_8 started!
[INFO] 2019-10-30 14:17:31.368955: Scenario process process_9 started!
[INFO] 2019-10-30 14:17:31.371023: Scenario process process_5 started!
[INFO] 2019-10-30 14:17:31.374728: Scenario process process_10 started!
[INFO] 2019-10-30 14:17:31.378094: Scenario process process_7 started!
[INFO] 2019-10-30 14:17:31.385544: Scenario process process_14 started!
[INFO] 2019-10-30 14:17:31.385730: Scenario process process_13 started!
[INFO] 2019-10-30 14:17:31.387299: Scenario process process_17 started!
[INFO] 2019-10-30 14:17:31.387620: Scenario process process_18 started!
[INFO] 2019-10-30 14:17:31.388648: Scenario process process_15 started!
[INFO] 2019-10-30 14:17:31.395610: Scenario process process_11 started!
[INFO] 2019-10-30 14:17:31.395818: Scenario process process_12 started!
[INFO] 2019-10-30 14:17:31.396179: Scenario loaded successfully. Wait 30.0 minutes before closing the terminal!
[INFO] 2019-10-30 14:17:31.400050: Scenario process process_19 started!
[INFO] 2019-10-30 14:17:31.400279: Scenario process process_16 started!
[INFO] 2019-10-30 14:31:47.698304: Scenario process process_0 started!
[INFO] 2019-10-30 14:31:47.699705: Scenario process process_1 started!
[INFO] 2019-10-30 14:31:47.701074: Scenario process process_2 started!
[INFO] 2019-10-30 14:31:47.703142: Scenario process process_3 started!
[INFO] 2019-10-30 14:31:47.705111: Scenario process process_4 started!
[INFO] 2019-10-30 14:31:47.707613: Scenario process process_6 started!
[INFO] 2019-10-30 14:31:47.715599: Scenario process process_8 started!
[INFO] 2019-10-30 14:31:47.717893: Scenario process process_5 started!
[INFO] 2019-10-30 14:31:47.721151: Scenario process process_10 started!
[INFO] 2019-10-30 14:31:47.724385: Scenario process process_7 started!
[INFO] 2019-10-30 14:31:47.729661: Scenario process process_11 started!
[INFO] 2019-10-30 14:31:47.730021: Scenario process process_13 started!
[INFO] 2019-10-30 14:31:47.738887: Scenario process process_12 started!
[INFO] 2019-10-30 14:31:47.740400: Scenario process process_15 started!
[INFO] 2019-10-30 14:31:47.741388: Scenario process process_16 started!
[INFO] 2019-10-30 14:31:47.746381: Scenario process process_14 started!
[INFO] 2019-10-30 14:31:47.751448: Scenario process process_17 started!
[INFO] 2019-10-30 14:31:47.751518: Scenario loaded successfully. Wait 10.0 minutes before closing the terminal!
[INFO] 2019-10-30 14:31:47.754709: Scenario process process_18 started!
[INFO] 2019-10-30 14:31:47.755884: Scenario process process_19 started!
[INFO] 2019-10-30 14:31:47.766966: Scenario process process_9 started!
[INFO] 2019-10-30 14:41:47.763781: process_16 stopped. Execution finished!
[INFO] 2019-10-30 14:41:47.813967: process_8 stopped. Execution finished!
[INFO] 2019-10-30 14:41:47.859556: process_18 stopped. Execution finished!
[INFO] 2019-10-30 14:41:47.944569: process_19 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.007349: process_5 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.111173: process_7 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.132706: process_11 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.140088: process_1 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.146912: process_6 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.203984: process_0 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.211564: process_13 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.287598: process_2 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.319283: process_9 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.329369: process_3 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.339388: process_17 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.356930: Script terminated successfully. uptime: 10.0 minutes
[INFO] 2019-10-30 14:41:48.370933: process_15 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.403058: process_12 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.410716: process_10 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.412640: process_14 stopped. Execution finished!
[INFO] 2019-10-30 14:41:48.428025: process_4 stopped. Execution finished!
[INFO] 2019-10-30 14:48:05.698391: process_19 stopped. Execution finished!
[INFO] 2019-10-30 14:49:22.450414: process_3 stopped. Execution finished!
[INFO] 2019-10-30 14:49:52.699059: process_13 stopped. Execution finished!
[INFO] 2019-10-30 14:50:05.861778: process_12 stopped. Execution finished!
[INFO] 2019-10-30 14:51:16.496097: process_4 stopped. Execution finished!
[INFO] 2019-10-30 14:51:55.509664: process_16 stopped. Execution finished!
[INFO] 2019-10-30 14:52:53.284733: process_18 stopped. Execution finished!
[INFO] 2019-10-30 14:54:20.423948: process_9 stopped. Execution finished!
[INFO] 2019-10-30 14:54:31.511281: process_0 stopped. Execution finished!
[INFO] 2019-10-30 14:55:02.349190: process_1 stopped. Execution finished!
[INFO] 2019-10-30 14:55:47.959453: process_15 stopped. Execution finished!
[INFO] 2019-10-30 14:56:06.785000: process_11 stopped. Execution finished!
[INFO] 2019-10-30 14:56:15.050055: process_7 stopped. Execution finished!
[INFO] 2019-10-30 14:56:59.969764: process_2 stopped. Execution finished!
[INFO] 2019-10-30 14:59:03.857146: process_5 stopped. Execution finished!
[INFO] 2019-10-30 15:02:56.635025: process_6 stopped. Execution finished!
[INFO] 2019-10-30 15:04:27.668449: process_8 stopped. Execution finished!
[INFO] 2019-10-30 15:08:13.954444: process_17 stopped. Execution finished!
[INFO] 2019-10-30 15:09:48.121919: Scenario process process_0 started!
[INFO] 2019-10-30 15:09:48.123502: Scenario process process_1 started!
[INFO] 2019-10-30 15:09:48.125130: Scenario process process_2 started!
[INFO] 2019-10-30 15:09:48.125765: Scenario process process_3 started!
[INFO] 2019-10-30 15:09:48.126435: Scenario process process_4 started!
[INFO] 2019-10-30 15:09:48.127689: Scenario process process_5 started!
[INFO] 2019-10-30 15:09:48.133615: Scenario process process_9 started!
[INFO] 2019-10-30 15:09:48.136942: Scenario process process_6 started!
[INFO] 2019-10-30 15:09:48.138440: Scenario process process_10 started!
[INFO] 2019-10-30 15:09:48.139663: Scenario process process_11 started!
[INFO] 2019-10-30 15:09:48.142513: Scenario process process_14 started!
[INFO] 2019-10-30 15:09:48.143960: Scenario process process_15 started!
[INFO] 2019-10-30 15:09:48.144492: Scenario process process_8 started!
[INFO] 2019-10-30 15:09:48.145767: Scenario process process_16 started!
[INFO] 2019-10-30 15:09:48.146855: Scenario process process_12 started!
[INFO] 2019-10-30 15:09:48.149959: Scenario loaded successfully. Wait 15.0 minutes before closing the terminal!
[INFO] 2019-10-30 15:09:48.150687: Scenario process process_7 started!
[INFO] 2019-10-30 15:09:48.150682: Scenario process process_13 started!
[INFO] 2019-10-30 15:09:48.151832: Scenario process process_19 started!
[INFO] 2019-10-30 15:09:48.155988: Scenario process process_18 started!
[INFO] 2019-10-30 15:09:48.156940: Scenario process process_17 started!
[INFO] 2019-10-30 15:11:39.508790: Scenario process process_0 started!
[INFO] 2019-10-30 15:11:39.510036: Scenario process process_1 started!
[INFO] 2019-10-30 15:11:39.511108: Scenario process process_2 started!
[INFO] 2019-10-30 15:11:39.512564: Scenario process process_3 started!
[INFO] 2019-10-30 15:11:39.514274: Scenario process process_4 started!
[INFO] 2019-10-30 15:11:39.521667: Scenario process process_7 started!
[INFO] 2019-10-30 15:11:39.523783: Scenario process process_5 started!
[INFO] 2019-10-30 15:11:39.527152: Scenario process process_10 started!
[INFO] 2019-10-30 15:11:39.532073: Scenario process process_8 started!
[INFO] 2019-10-30 15:11:39.539485: Scenario process process_15 started!
[INFO] 2019-10-30 15:11:39.541913: Scenario process process_11 started!
[INFO] 2019-10-30 15:11:39.548422: Scenario process process_18 started!
[INFO] 2019-10-30 15:11:39.548875: Scenario process process_13 started!
[INFO] 2019-10-30 15:11:39.549420: Scenario process process_14 started!
[INFO] 2019-10-30 15:11:39.549715: Scenario process process_12 started!
[INFO] 2019-10-30 15:11:39.553372: Scenario loaded successfully. Wait 15.0 minutes before closing the terminal!
[INFO] 2019-10-30 15:11:39.556142: Scenario process process_17 started!
[INFO] 2019-10-30 15:11:39.560497: Scenario process process_16 started!
[INFO] 2019-10-30 15:11:39.560915: Scenario process process_6 started!
[INFO] 2019-10-30 15:11:39.561103: Scenario process process_19 started!
[INFO] 2019-10-30 15:11:39.561220: Scenario process process_9 started!
