Enter your jmeter path (Ex:- /home/user/Documents/apache-jmeter-5.1.1/bin)
Creating summariser <summary>
Created the tree successfully using API Scenario - multiple end users.jmx
Starting the test @ Wed Oct 30 14:15:03 IST 2019 (1572425103799)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +      1 in 00:00:01 =    1.0/s Avg:   778 Min:   778 Max:   778 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
summary +     33 in 00:00:25 =    1.3/s Avg:   207 Min:    12 Max:  1157 Err:     0 (0.00%) Active: 1 Started: 3 Finished: 2
summary =     34 in 00:00:26 =    1.3/s Avg:   224 Min:    12 Max:  1157 Err:     0 (0.00%)
summary +     15 in 00:00:30 =    0.5/s Avg:    19 Min:    11 Max:    29 Err:     0 (0.00%) Active: 1 Started: 3 Finished: 2
summary =     49 in 00:00:57 =    0.9/s Avg:   161 Min:    11 Max:  1157 Err:     0 (0.00%)
summary +    105 in 00:00:27 =    3.9/s Avg:   161 Min:    12 Max:   417 Err:     0 (0.00%) Active: 0 Started: 4 Finished: 4
summary =    154 in 00:01:24 =    1.8/s Avg:   161 Min:    11 Max:  1157 Err:     0 (0.00%)
Tidying up ...    @ Wed Oct 30 14:16:27 IST 2019 (1572425187933)
... end of run
Enter your jmeter path (Ex:- /home/user/Documents/apache-jmeter-5.1.1/bin)
Creating summariser <summary>
Created the tree successfully using Generate token list.jmx
Starting the test @ Wed Oct 30 14:16:49 IST 2019 (1572425209838)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary =    160 in 00:00:03 =   47.9/s Avg:    13 Min:     5 Max:   277 Err:     0 (0.00%)
Tidying up ...    @ Wed Oct 30 14:16:53 IST 2019 (1572425213582)
... end of run
Enter filename (without file extension): 
Enter script execution time in minutes: 
Traffic Tool Stopped Successfully
Enter filename (without file extension): 
Enter script execution time in minutes: 
[INFO] Scenario loaded successfully. Wait 10.0 minutes before closing the terminal!
[INFO] Script terminated successfully. uptime: 10.0 minutes
Enter filename (without file extension): 
Enter script execution time in minutes: 
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-17:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-19:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "invoke_API.py", line 211, in runInvoker
    no_of_requests = scenario_row[0] - random.randint(0, no_of_requests)
UnboundLocalError: local variable 'no_of_requests' referenced before assignment
Enter filename (without file extension): 
Enter script execution time in minutes: 
Traffic Tool Stopped Successfully
